name: Cypress Tests

on: 
  push: 
    branches:
      - main
      - dev
  schedule: 
    - cron: 15 13 * * 5
env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  DATABASE_API_URL: ${{ secrets.DATABASE_API_URL}}
  DATABASE_API_KEY: ${{ secrets.DATABASE_API_KEY}}
  DATABASE_SOURCE: ${{ secrets.DATABASE_SOURCE}}
  DATABASE_NAME: ${{ secrets.DATABASE_NAME}}
  DATABASE_COLLECTION: ${{ secrets.DATABASE_COLLECTION}}
  DATABASE_USER_ID: ${{ secrets.DATABASE_USER_ID}}
  GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID}}
  GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET}}
  GOOGLE_REFRESH_TOKEN: ${{ secrets.GOOGLE_REFRESH_TOKEN}}
  NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET}}
  NEXTAUTH_URL:  ${{ secrets.NEXTAUTH_URL}}
  UNIT_TESTER_ID: ${{ secrets.UNIT_TESTER_ID }}
  UNIT_TEST_LIST_ID: ${{ secrets.UNIT_TEST_LIST_ID }}
  UNIT_TEST_HOUSEHOLD_ID: ${{ secrets.UNIT_TEST_HOUSEHOLD_ID }}
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm start
