name: Cypress Tests

on: push
env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  DATABASE_API_URL: ${{ secrets.DATABASE_API_URL}}
  DATABASE_API_KEY: ${{ secrets.DATABASE_API_KEYD}}
  DATABASE_SOURCE: ${{ secrets.DATABASE_SOURCE}}
  DATABASE_NAME: ${{ secrets.DATABASE_NAME}}
  DATABASE_COLLECTION: ${{ secrets.DATABASE_COLLECTIONL}}
  DATABASE_USER_ID: ${{ secrets.DATABASE_USER_ID}}
  GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID}}
  GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET}}
  GOOGLE_REFRESH_TOKEN: ${{ secrets.GOOGLE_REFRESH_TOKEN}}
  NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET}}
  NEXTAUTH_URL:  ${{ secrets.NEXTAUTH_URL}}
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm start
